# version of the .dockstore.yml schema (1.2)
version: 1.2
# An array of workflows. Each element corresponds to a workflow on Dockstore.
workflows:
    # The optional workflow name for a workflow
  - name: NPM-sample-qc
    # subclass: CWL, WDL, NFL (Nextflow), or GALAXY.
    subclass: NFL
    # The absolute path to the primary descriptor file in the Git repository.
    # - Nextflow primary descriptor is a nextflow.config file.
    primaryDescriptorPath: /nextflow.config
    # An optional array of absolute paths to test parameter files in the Git repository.
    # testParameterFiles:
    # An optional array of authorship information.
    authors:
      - name: Justin Jeyakani
        email:
    # The optional filters section allow specifying sets of Git branches and tags to include for the workflow.
    filters:
      branches: 
        - master
