# Dockstore config version, not pipeline version
version: 1.2
workflows:
  - name: NPM-sample-qc
    subclass: nfl
    primaryDescriptorPath: /nextflow.config
    publish: True
    authors:
      - name: Justin Jeyakani
        orcid: 0000-0002-1788-0417
      - name: Mar Gonzalez-Porta
        orcid:
      - name: Maxime HEBRARD
        orcid: 0000-0003-2346-4513
      - name: Rodrigo Toro
        orcid:
      - name: Nicolas Bertin
        orcid: 0000-0002-9835-9606 
