name: npm-sample-qc
channels:
    - bioconda
    - conda-forge
    - defaults
dependencies:
    - python=3.7
    - bcftools=1.10.2
    - samtools=1.10
    - picard=2.21.7
    - verifybamid2=1.0.5
    - bedtools=2.29.2
