name: npm-sample-qc
channels:
    - bioconda
    - conda-forge
    - defaults 
dependencies:
    - python=3.7
    - samtools=1.15
    - bcftools=1.15
    - picard=2.27.0
    - bedtools=2.29.2
    - mosdepth=0.3.3
    - verifybamid2=2.0.1  
