Bootstrap: docker
From: continuumio/miniconda

%environment
    PATH=/opt/conda/envs/npm-sample-qc/bin:$PATH
    export PATH

%files
    conda_env.yml /

%post
    # Update the base version of conda
    /opt/conda/bin/conda update -n base conda

    # Create conda environment from template
    /opt/conda/bin/conda env create -f /conda_env.yml
    /opt/conda/bin/conda clean -a

    # Add sg10k-cov binary
    apt-get update -y && \
      apt-get install --fix-missing -y build-essential linux-libc-dev zlib1g-dev libbz2-dev && \
      git clone https://github.com/c-BIG/sg10k-cov.git && \
      cd sg10k-cov/ && \
      git checkout 6b74ab8 && \
      bash make.sh && \
      cp sg10k-cov-062017.sh samtools-M /usr/local/bin/

    # NSCC-specific directories
    mkdir /data /seq /secure /scratch
